pagopa/devopslab-infra

src/core/.terraform.lock.hcl
src/core/98_grafana.tf
src/pillar/04_acr.tf
src/pillar/04_monitor.tf
src/pillar/99_variables.tf

feat: Add Grafana stack

---

src/.env/dev/terraform.tfvars

aks sku to b2ms

---

src/.env/dev/kubernetes.tfvars
src/core/99_main.tf
src/k8s/.terraform.lock.hcl
src/k8s/01_namespaces.tf
src/k8s/02_keda_controller.tf
src/k8s/03_serviceaccounts_azure_devops.tf
src/k8s/98_helm_template_namespace.tf

feat: Add Keda

---

src/k8s/02_ingress_controller.tf
src/k8s/02_keda_controller.tf
src/k8s/98_helm_template_namespace.tf
src/k8s/99_variables.tf
src/k8s/README.md
src/k8s/ingress/autoscaling.yaml.tpl

feat: Enable Keda autoscaling on ingress controller

---

src/.env/dev/terraform.tfvars
src/core/02_appgateway.tf
src/core/99_variables.tf

fix: App gateway can be deleted

---

src/.env/dev/terraform.tfvars
src/domains/diego-common/00_network.tf
src/domains/diego-common/README.md
src/pillar/.terraform.lock.hcl
src/pillar/02_vpn.tf
src/pillar/99_variables.tf
src/pillar/README.md
src/pillar/dns/Corefile

- added vpn code
- added dns forwarder
Allow to test how vpn works
---

feat: added dns forwarder

---

.pre-commit-config.yaml
src/core/00_monitor.tf
src/core/05_monitoring.tf
src/core/README.md

added alert error for budgets
---

feat: Add-alerts-prod-error

---

src/aks-platform/.terraform.lock.hcl
src/aks-platform/01_network_aks.tf
src/aks-platform/03_aks.tf
src/aks-platform/04_rbac.tf
src/aks-platform/05_ingress.tf
src/aks-platform/05_keda.tf
src/aks-platform/99_locals.tf
src/aks-platform/99_main.tf
src/aks-platform/env/dev01/backend.ini
src/aks-platform/env/dev01/terraform.tfvars

fix: Aks-migration-v3

---

src/aks-platform/01_network_aks.tf
src/aks-platform/04_rbac.tf
src/aks-platform/05_ingress.tf
src/aks-platform/05_keda.tf
src/aks-platform/99_main.tf
src/domains/diego-app/00_network.tf
src/domains/diego-app/01_network.tf
src/domains/diego-app/02_namespace_domain.tf
src/domains/diego-app/99_locals.tf
src/domains/diego-app/99_variables.tf
src/domains/diego-app/env/dev/terraform.tfvars
src/domains/diego-common/env/dev/terraform.tfvars

feat: init diego-app domain into aks cluster

---

.github/workflows/pr-title.yml
.github/workflows/release.yml
.github/workflows/static_analysis.yml

feat: Added github static analysis

---

src/domains/diego-app/05_container_app_amassador.tf
src/domains/diego-app/05_container_app_devops_color_java.tf
src/domains/diego-app/99_variables.tf
src/domains/diego-app/README.md
src/domains/diego-app/container-app/ambassador.yaml.tpl
src/domains/diego-app/container-app/devops-java-springboot-color.yaml.tpl

feat: Container-app-ambassador-deployed

---

.identity/.terraform.lock.hcl
.identity/02_application_environment_ci.tf
.identity/03_github_environment_ci.tf
.identity/99_main.tf
.identity/99_outputs.tf
.identity/README.md
.identity/modules/app-github-runner-ci/README.md
.identity/modules/app-github-runner-ci/main.tf
.identity/modules/app-github-runner-ci/output.tf
.identity/modules/app-github-runner-ci/variables.tf
.identity/modules/github-environment-secrets/README.md
.identity/modules/github-environment-secrets/main.tf
.identity/modules/github-environment-secrets/variables.tf
.utils/terraform_run_all.sh
src/domains/diego-app/04_aks_aad_github.tf
src/domains/diego-app/README.md

- created module for github runner ci
- created module for github env secrets
- fix role assignments
- other minor fixes
Create a module that simplify the creation of a runner ci
---

feat: Modularize github runner CI

---

.github/workflows/dev_cd_diego_app.yml
.identity/02_application_environment_cd.tf
.identity/03_github_environment_cd.tf
.identity/99_outputs.tf
.identity/README.md
.identity/env/dev/terraform.tfvars
.identity/modules/app-github-runner-cd/README.md
.identity/modules/app-github-runner-cd/main.tf
.identity/modules/app-github-runner-cd/output.tf
.identity/modules/app-github-runner-cd/variables.tf
.identity/modules/app-github-runner-ci/README.md
.identity/modules/app-github-runner-ci/variables.tf
src/domains/diego-app/README.md
src/domains/diego-app/deleteme-namespace.tf

feat: Modularize-github-runner-cd

---

.github/workflows/dev_cd_diego_app.yml
.identity/03_github_environment_cd.tf
.identity/README.md
.identity/modules/app-github-runner-generator/README.md
.identity/modules/app-github-runner-generator/main.tf
.identity/modules/app-github-runner-generator/output.tf
.identity/modules/app-github-runner-generator/variables.tf
src/domains/diego-app/02_namespace_domain.tf
src/domains/diego-app/04_aks_aad_github.tf
src/domains/diego-app/README.md
src/domains/diego-app/deleteme-namespace.tf

feat: Github action CD works

---

src/domains/legacy-common/.terraform.lock.hcl
src/domains/legacy-common/00_azuread.tf
src/domains/legacy-common/00_monitor.tf
src/domains/legacy-common/00_network.tf
src/domains/legacy-common/99_main.tf
src/domains/legacy-common/99_main.tf.ci
src/domains/legacy-common/99_variables.tf
src/domains/legacy-common/README.md
src/domains/legacy-common/env/dev/backend.ini
src/domains/legacy-common/env/dev/backend.tfvars
src/domains/legacy-common/env/dev/terraform.tfvars
src/domains/legacy-common/terraform.sh

breaking: Created legacy-common domain for azurerm v2

---

src/domains/legacy-common/.terraform.lock.hcl
src/domains/legacy-common/01_storage.tf
src/domains/legacy-common/99_main.tf
src/domains/legacy-common/99_main.tf.ci
src/domains/legacy-common/README.md

feat: Test-bob-storage-soft-delete

---

.devops/diego-code-review-pipelines.yml
.devops/diego-deploy-pipelines.yml
src/aks-platform/k8setup.sh
src/domains/diego-app/03_serviceaccounts_azure_devops.tf
src/domains/diego-app/99_variables.tf
src/domains/diego-app/README.md
src/packer/01_azure_devops_agent.tf
src/packer/README.md
src/pillar/04_azure_devops_agent.tf
src/pillar/99_variables.tf
src/pillar/README.md

feat: Upgrated devops scaleset agent

---

.devops/diego-code-review-pipelines.yml
.devops/diego-deploy-pipelines.yml
.github/workflows/dev_cd_diego_app.yml
.github/workflows/dev_cd_diego_common.yml
.github/workflows/dev_ci_diego_app.yml
.github/workflows/dev_ci_diego_common.yml
.github/workflows/dev_drift_diego_common.yml
src/domains/diego-app/05_configmaps_mocks.tf
src/domains/diego-app/README.md
src/domains/diego-app/terraform.sh

feat: Improve deploy pipelines diego

---

src/.env/dev/terraform.tfvars
src/pillar/02_vpn.tf
src/pillar/99_main.tf
src/pillar/99_main.tf.ci
src/pillar/README.md

feat: Vpn re-enabled

---

src/domains/diego-container-apps/01_container_app_0.tf
src/domains/diego-container-apps/01_cosmos_db.tf
src/domains/diego-container-apps/02_container_app_env_dapr.tf
src/domains/diego-container-apps/02_container_app_env_diego.tf
src/domains/diego-container-apps/03_container_app_devops_darp.tf
src/domains/diego-container-apps/99_variables.tf
src/domains/diego-container-apps/README.md
src/domains/diego-container-apps/env/dev/terraform.tfvars

feat: Added features flags for diego-container-app

---

src/elk-monitoring/05_elastic_stack.tf
src/elk-monitoring/README.md

feat: ECK upgrated to 2.9

---

src/aks-platform/03_prometheus_managed.tf
src/grafana-monitoring/.terraform.lock.hcl
src/grafana-monitoring/00_azuread.tf
src/grafana-monitoring/02_grafana_managed.tf
src/grafana-monitoring/99_locals.tf
src/grafana-monitoring/99_main.tf
src/grafana-monitoring/99_variables.tf
src/grafana-monitoring/README.md
src/grafana-monitoring/dash/jmx-exporter.json
src/grafana-monitoring/env/dev01/backend.ini
src/grafana-monitoring/env/dev01/backend.tfvars
src/grafana-monitoring/env/dev01/terraform.tfvars
src/grafana-monitoring/terraform.sh

feat: Added Grafana-managed

---

src/aks-platform/02_aks.tf
src/aks-platform/99_locals.tf
src/aks-platform/README.md
src/core/02_dns_private.tf
src/core/README.md
src/coreplus/01_network_aks_platform.tf
src/coreplus/README.md
src/domains/blueprint-common/.terraform.lock.hcl
src/domains/blueprint-common/00_azuread.tf
src/domains/blueprint-common/00_monitor.tf
src/domains/blueprint-common/00_network.tf
src/domains/blueprint-common/01_keyvault_0.tf
src/domains/blueprint-common/99_main.tf
src/domains/blueprint-common/99_main.tf.ci
src/domains/blueprint-common/99_variables.tf
src/domains/blueprint-common/README.md
src/domains/blueprint-common/env/dev/backend.ini
src/domains/blueprint-common/env/dev/backend.tfvars
src/domains/blueprint-common/env/dev/terraform.tfvars
src/domains/blueprint-common/terraform.sh
src/packer/README.md

Added a space to test helm and blueprints
---

feat: Added blueprint-common

---

src/domains/blueprint-app/.terraform.lock.hcl
src/domains/blueprint-app/00_aks.tf
src/domains/blueprint-app/00_azuread.tf
src/domains/blueprint-app/00_key_vault.tf
src/domains/blueprint-app/00_monitor.tf
src/domains/blueprint-app/00_network.tf
src/domains/blueprint-app/01_keyvault.tf
src/domains/blueprint-app/01_network.tf
src/domains/blueprint-app/02_namespace_domain.tf
src/domains/blueprint-app/03_serviceaccounts_azure_devops.tf
src/domains/blueprint-app/80_middleware_tools.tf
src/domains/blueprint-app/99_main.tf
src/domains/blueprint-app/99_main.tf.ci
src/domains/blueprint-app/99_variables.tf
src/domains/blueprint-app/README.md
src/domains/blueprint-app/env/dev/backend.ini
src/domains/blueprint-app/env/dev/backend.tfvars
src/domains/blueprint-app/env/dev/terraform.tfvars
src/domains/blueprint-app/terraform.sh

Added blueprint-app to allow test of kubernetes and helm apps
---

feat: Added blueprint-app

---

src/aks-platform/02_aks.tf
src/aks-platform/02_aks_storage.tf
src/aks-platform/README.md

feat: Aks added storage class for HDD

---

src/domains/blueprint-app/02_namespace_domain.tf
src/domains/blueprint-app/README.md
src/domains/blueprint-common/README.md

feat: Added pvc for hdd

---

src/aks-platform/02_aks_storage.tf
src/aks-platform/03_monitoring.tf

feat: Updated prometheus monitoring installation

---

src/aks-platform/02_aks_0.tf
src/aks-platform/02_aks_storage.tf
src/aks-platform/03_monitoring.tf
src/aks-platform/99_variables.tf
src/aks-platform/README.md
src/aks-platform/env/dev01/terraform.tfvars
src/elk-monitoring/02_aks.tf
src/elk-monitoring/99_variables.tf
src/elk-monitoring/README.md
src/elk-monitoring/env/dev01/terraform.tfvars
src/packer/01_azure_devops_agent.tf
src/packer/README.md

feat: Created spoted instance code for future use

---

src/aks-platform/env/dev01/terraform.tfvars

feat: Upgrated keda to 2.12.0

---

src/aks-platform/02_aks_storage.tf
src/aks-platform/README.md
src/domains/blueprint-app/02_namespace_domain.tf
src/domains/blueprint-app/README.md
src/elk-monitoring/env/dev01/terraform.tfvars

fix: New-pvc-claim

---

src/core/03_apim_0.tf
src/core/99_variables.tf
src/core/README.md
src/domains/umberto-common/.terraform.lock.hcl
src/domains/umberto-common/00_azuread.tf
src/domains/umberto-common/00_monitor.tf
src/domains/umberto-common/01_keyvault_0.tf
src/domains/umberto-common/99_main.tf
src/domains/umberto-common/99_main.tf.ci
src/domains/umberto-common/99_variables.tf
src/domains/umberto-common/README.md
src/domains/umberto-common/env/dev/backend.ini
src/domains/umberto-common/env/dev/backend.tfvars
src/domains/umberto-common/env/dev/terraform.tfvars
src/domains/umberto-common/terraform.sh

feat: Add umberto domain

---

.github/workflows/static_analysis.yml
.github/workflows/static_analysis_main.yml
.github/workflows/static_analysis_pr.yml
README.md
src/elk-monitoring/99_main.tf.ci
src/grafana-monitoring/99_main.tf.ci

feat: static analysis main action

---

src/.env/dev/terraform.tfvars
src/core/00_network.tf
src/core/09_dns_forwarder.tf
src/core/99_variables.tf
src/core/README.md
src/packer/02_dns_forwarder.tf
src/packer/99_variables.tf
src/packer/README.md
src/packer/env/dev/terraform.tfvars

- Added dns forwarder packer image
- Added vms scale set
- Added a load balancer with backend container instances and vms scale set.
---

feat: Add scale set for dns forwarder

---

src/.env/dev/terraform.tfvars
src/core/.terraform.lock.hcl
src/core/09_dns_forwarder.tf
src/core/99_variables.tf
src/core/README.md

Refactoring dns forwarder with new module
---

fix: Dns forwarder

---

src/aks-platform/.terraform.lock.hcl
src/aks-platform/01_network_aks.tf
src/aks-platform/02_aks_0.tf
src/aks-platform/02_aks_storage.tf
src/aks-platform/03_monitoring.tf
src/aks-platform/05_argocd.tf
src/aks-platform/05_keda.tf
src/aks-platform/99_main.tf
src/aks-platform/README.md

- added storage options for aks
- added pvc for blueprint file share
Allow to use pod with shared files
---

feat: Added storage option and pvc

---

src/.env/dev/terraform.tfvars
src/core/01_network.tf
src/core/02_dns_private.tf
src/core/02_dns_public.tf
src/core/99_variables.tf
src/core/README.md

feat: Vnet on Italy

---

src/aks-platform/05_argocd.tf
src/aks-platform/05_ingress.tf
src/aks-platform/ingress/loadbalancer.yaml.tpl
src/core/01_network.tf

fix: Ingress internal loadbalancer

---

.pre-commit-config.yaml
src/aks-platform/05_argocd.tf

feat: Argocd update to v6.7.11

---

src/domains/blueprint-app/env/dev/terraform.tfvars
src/domains/diego-app/.terraform.lock.hcl
src/domains/diego-app/00_acr.tf
src/domains/diego-app/00_key_vault.tf
src/domains/diego-app/01_network.tf
src/domains/diego-app/02_namespace_domain.tf
src/domains/diego-app/03_serviceaccounts_azure_devops.tf
src/domains/diego-app/04_aks_aad_github.tf
src/domains/diego-app/05_configmaps_mocks.tf
src/domains/diego-app/80_middleware_tools.tf
src/domains/diego-app/99_main.tf
src/domains/diego-app/99_variables.tf
src/domains/diego-app/README.md
src/domains/diego-app/env/dev/backend.tfvars
src/domains/diego-app/env/dev/terraform.tfvars
src/domains/diego-common/.terraform.lock.hcl
src/domains/diego-common/01_keyvault_0.tf
src/domains/diego-common/08_cdn.tf
src/domains/diego-common/09_let_encrypt_credentials.tf
src/domains/diego-common/99_main.tf
src/domains/diego-common/99_variables.tf
src/domains/diego-common/README.md
src/domains/diego-common/env/dev/backend.tfvars
src/domains/diego-common/env/dev/terraform.tfvars

feat: Diego-on-italynorth

---

src/domains/testit-app/.terraform.lock.hcl
src/domains/testit-app/02_namespace_domain.tf
src/domains/testit-app/03_serviceaccounts_azure_devops.tf
src/domains/testit-app/04_k8s_storage.tf
src/domains/testit-app/80_middleware_tools.tf
src/domains/testit-app/99_main.tf
src/domains/testit-app/README.md

fix: TLS checker for testit-app

---

src/domains/testit-app/00_network.tf
src/domains/testit-app/01_network.tf
src/domains/testit-app/01_nodepool_dedicated.tf
src/domains/testit-app/99_variables.tf
src/domains/testit-app/README.md
src/domains/testit-app/env/itn-dev/terraform.tfvars

feat: testit taints for nodepool

---

src/aks-platform/.terraform.lock.hcl
src/aks-platform/01_network.tf
src/aks-platform/05_argocd.tf
src/aks-platform/README.md
src/core/02_dns_private.tf
src/core/README.md

fix: dns private link to Italy and Argocd-re-enabled

---

src/aks-platform/03_monitoring.tf
src/aks-platform/README.md

feat: Updated prometheus version

---

src/aks-platform/.terraform.lock.hcl
src/aks-platform/02_aks_0.tf
src/aks-platform/02_aks_storage.tf
src/aks-platform/03_aks_middleware.tf
src/aks-platform/05_argocd.tf
src/aks-platform/05_keda.tf
src/aks-platform/99_main.tf
src/aks-platform/README.md
src/packer/01_azure_devops_agent.tf
src/packer/02_dns_forwarder.tf
src/packer/README.md

feat: AKS added cilium network

---

src/aks-platform/02_aks_0.tf

feat: AKS Workload identity enabled

---

.github/workflows/static_analysis_pr.yml
src/github-runner/01_github_identity.tf
src/github-runner/02_container_app_jobs.tf
src/github-runner/README.md

- Set Reader on subscription and other
- add "Azure Kubernetes Service Cluster User Role"
Restrict the permission of github runner container app instance
---

fix: [PAYMCLOUD-109] Update roles in GitHub runner TF files to fix permissions

---

src/aks-platform/05_argocd.tf
src/aks-platform/env/itn-dev/terraform.tfvars
src/core/env/dev/terraform.tfvars
src/domains/diego-app/.terraform.lock.hcl
src/domains/diego-app/05_argocd.tf
src/domains/diego-app/99_main.tf
src/domains/diego-app/99_variables.tf
src/domains/diego-app/README.md

- removed root app for argocd
- updated vmss for azdo with the new image
---

feat: ArgoCD removed root app and used plain apps

---

scripts/terraform.sh
src/0-entra/.terraform.lock.hcl
src/0-entra/00_kv.tf
src/0-entra/00_users.tf
src/0-entra/10_argocd.tf
src/0-entra/99_locals.tf
src/0-entra/99_main.tf
src/0-entra/99_variables.tf
src/0-entra/README.md
src/0-entra/env/itn-dev/backend.ini
src/0-entra/env/itn-dev/backend.tfvars
src/0-entra/env/itn-dev/terraform.tfvars
src/0-entra/terraform.sh
src/aks-platform/03_monitoring.tf
src/aks-platform/05_argocd.tf
src/aks-platform/99_locals.tf
src/aks-platform/99_variables.tf
src/aks-platform/README.md
src/aks-platform/argocd/argocd_helm_setup_values.yaml
src/aks-platform/env/itn-dev/terraform.tfvars

- entra app for argocd
- argocd configured to use entra oicd login
Allow users to login with own account 
---

feat: ArgoCD login with entra app

---

src/core/04_azure_devops_agent.tf
src/core/99_variables.tf
src/core/README.md
src/core/env/dev/terraform.tfvars
src/packer/01_azure_devops_agent.tf
src/packer/README.md
src/packer/env/dev/terraform.tfvars

feat: Update packer images for azdo and dns forwarder
